# .github/workflows/test.yml

name: SwearIT Contract Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          npm install
      - name: Compile contracts
        run: |
          npx hardhat compile
      - name: Run tests
        run: |
          npx hardhat test
